name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      SECRET_KEY: Lucas55418794*
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: django_db
      SQL_USER: user
      SQL_PASSWORD: password
      SQL_HOST: localhost
      SQL_PORT: 5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Set up Database
      run: |
        poetry run python manage.py migrate
    - name: Run Tests
      run: |
        poetry run python manage.py test

